apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio-container
        image: docker.io/lolosposaro/portfolio:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ENV_VAR_NAME
          value: "value" 
        - name: additional-env-var
          value: "additional-value"
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP