on:
  workflow_call:

env: 
  DISPATCH_REPO_NAME: ""
  
jobs:
  commands:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token for Github App
        id: generate-token_tf_nx
        uses: tibdex/github-app-token@v2
        with:
            app_id: ${{ secrets.NX_INFRA_SELF_SERVICE_APPID }}
            private_key: ${{ secrets.NX_INFRA_SELF_SERVICE_SECRET  }}
            repositories: >-
              ["${{env.DISPATCH_REPO_NAME}}", "${{ github.event.repository.name }}"]
            revoke: false 
      # Advanced JSON configuration
      - name: Commands Dispatcher 
        id: scd
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ steps.generate-token_tf_nx.outputs.token }}
          config: >
            [
              {
                "command": "env-var",
                "permission": "none",
                "issue_type": "issue",
                "repository": "lolosposaro/${{ env.DISPATCH_REPO_NAME}}"
              },
              {
                "command": "help",
                "permission": "none",
                "issue_type": "issue",
                "repository": "BritishAirways-Nexus/${{ env.DISPATCH_REPO_NAME}}"
              }
            ]
