on:
  workflow_call:

env: 
  DISPATCH_REPO_NAME: "lolosposaro.github.io"
  
jobs:
  commands:
    runs-on: ubuntu-latest
    steps:

      - name: Commands Dispatcher 
        id: scd
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.MY_PAT }}
          config: >
            [
              {
                "command": "env-var",
                "permission": "none",
                "issue_type": "issue",
                "repository": "lolosposaro/${{ env.DISPATCH_REPO_NAME}}"
              },
              {
                "command": "help",
                "permission": "none",
                "issue_type": "issue",
                "repository": "lolosposaro/${{ env.DISPATCH_REPO_NAME}}"
              }
            ]
